// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protocolBuffer/Table.proto

package protocolBuffer;

public final class TableProtos {
  private TableProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TableOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocolBuffer.Table)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string tableName = 1;</code>
     */
    boolean hasTableName();
    /**
     * <code>required string tableName = 1;</code>
     */
    java.lang.String getTableName();
    /**
     * <code>required string tableName = 1;</code>
     */
    com.google.protobuf.ByteString
        getTableNameBytes();

    /**
     * <code>required int32 columnsNumber = 2;</code>
     */
    boolean hasColumnsNumber();
    /**
     * <code>required int32 columnsNumber = 2;</code>
     */
    int getColumnsNumber();

    /**
     * <code>required int32 rowsNumber = 3;</code>
     */
    boolean hasRowsNumber();
    /**
     * <code>required int32 rowsNumber = 3;</code>
     */
    int getRowsNumber();

    /**
     * <code>repeated int32 columnTypes = 4;</code>
     */
    java.util.List<java.lang.Integer> getColumnTypesList();
    /**
     * <code>repeated int32 columnTypes = 4;</code>
     */
    int getColumnTypesCount();
    /**
     * <code>repeated int32 columnTypes = 4;</code>
     */
    int getColumnTypes(int index);

    /**
     * <code>repeated string columnNames = 5;</code>
     */
    java.util.List<java.lang.String>
        getColumnNamesList();
    /**
     * <code>repeated string columnNames = 5;</code>
     */
    int getColumnNamesCount();
    /**
     * <code>repeated string columnNames = 5;</code>
     */
    java.lang.String getColumnNames(int index);
    /**
     * <code>repeated string columnNames = 5;</code>
     */
    com.google.protobuf.ByteString
        getColumnNamesBytes(int index);

    /**
     * <code>repeated .protocolBuffer.Table.Row rows = 6;</code>
     */
    java.util.List<protocolBuffer.TableProtos.Table.Row> 
        getRowsList();
    /**
     * <code>repeated .protocolBuffer.Table.Row rows = 6;</code>
     */
    protocolBuffer.TableProtos.Table.Row getRows(int index);
    /**
     * <code>repeated .protocolBuffer.Table.Row rows = 6;</code>
     */
    int getRowsCount();
    /**
     * <code>repeated .protocolBuffer.Table.Row rows = 6;</code>
     */
    java.util.List<? extends protocolBuffer.TableProtos.Table.RowOrBuilder> 
        getRowsOrBuilderList();
    /**
     * <code>repeated .protocolBuffer.Table.Row rows = 6;</code>
     */
    protocolBuffer.TableProtos.Table.RowOrBuilder getRowsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protocolBuffer.Table}
   */
  public  static final class Table extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocolBuffer.Table)
      TableOrBuilder {
    // Use Table.newBuilder() to construct.
    private Table(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Table() {
      tableName_ = "";
      columnsNumber_ = 0;
      rowsNumber_ = 0;
      columnTypes_ = java.util.Collections.emptyList();
      columnNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      rows_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Table(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              tableName_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              columnsNumber_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              rowsNumber_ = input.readInt32();
              break;
            }
            case 32: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                columnTypes_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000008;
              }
              columnTypes_.add(input.readInt32());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008) && input.getBytesUntilLimit() > 0) {
                columnTypes_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000008;
              }
              while (input.getBytesUntilLimit() > 0) {
                columnTypes_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                columnNames_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              columnNames_.add(bs);
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                rows_ = new java.util.ArrayList<protocolBuffer.TableProtos.Table.Row>();
                mutable_bitField0_ |= 0x00000020;
              }
              rows_.add(
                  input.readMessage(protocolBuffer.TableProtos.Table.Row.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          columnTypes_ = java.util.Collections.unmodifiableList(columnTypes_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          columnNames_ = columnNames_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          rows_ = java.util.Collections.unmodifiableList(rows_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocolBuffer.TableProtos.internal_static_protocolBuffer_Table_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocolBuffer.TableProtos.internal_static_protocolBuffer_Table_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocolBuffer.TableProtos.Table.class, protocolBuffer.TableProtos.Table.Builder.class);
    }

    public interface RowOrBuilder extends
        // @@protoc_insertion_point(interface_extends:protocolBuffer.Table.Row)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>repeated string columnValue = 1;</code>
       */
      java.util.List<java.lang.String>
          getColumnValueList();
      /**
       * <code>repeated string columnValue = 1;</code>
       */
      int getColumnValueCount();
      /**
       * <code>repeated string columnValue = 1;</code>
       */
      java.lang.String getColumnValue(int index);
      /**
       * <code>repeated string columnValue = 1;</code>
       */
      com.google.protobuf.ByteString
          getColumnValueBytes(int index);
    }
    /**
     * Protobuf type {@code protocolBuffer.Table.Row}
     */
    public  static final class Row extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:protocolBuffer.Table.Row)
        RowOrBuilder {
      // Use Row.newBuilder() to construct.
      private Row(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Row() {
        columnValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Row(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                  columnValue_ = new com.google.protobuf.LazyStringArrayList();
                  mutable_bitField0_ |= 0x00000001;
                }
                columnValue_.add(bs);
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
            columnValue_ = columnValue_.getUnmodifiableView();
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocolBuffer.TableProtos.internal_static_protocolBuffer_Table_Row_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocolBuffer.TableProtos.internal_static_protocolBuffer_Table_Row_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocolBuffer.TableProtos.Table.Row.class, protocolBuffer.TableProtos.Table.Row.Builder.class);
      }

      public static final int COLUMNVALUE_FIELD_NUMBER = 1;
      private com.google.protobuf.LazyStringList columnValue_;
      /**
       * <code>repeated string columnValue = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getColumnValueList() {
        return columnValue_;
      }
      /**
       * <code>repeated string columnValue = 1;</code>
       */
      public int getColumnValueCount() {
        return columnValue_.size();
      }
      /**
       * <code>repeated string columnValue = 1;</code>
       */
      public java.lang.String getColumnValue(int index) {
        return columnValue_.get(index);
      }
      /**
       * <code>repeated string columnValue = 1;</code>
       */
      public com.google.protobuf.ByteString
          getColumnValueBytes(int index) {
        return columnValue_.getByteString(index);
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        for (int i = 0; i < columnValue_.size(); i++) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, columnValue_.getRaw(i));
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        {
          int dataSize = 0;
          for (int i = 0; i < columnValue_.size(); i++) {
            dataSize += computeStringSizeNoTag(columnValue_.getRaw(i));
          }
          size += dataSize;
          size += 1 * getColumnValueList().size();
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof protocolBuffer.TableProtos.Table.Row)) {
          return super.equals(obj);
        }
        protocolBuffer.TableProtos.Table.Row other = (protocolBuffer.TableProtos.Table.Row) obj;

        boolean result = true;
        result = result && getColumnValueList()
            .equals(other.getColumnValueList());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptorForType().hashCode();
        if (getColumnValueCount() > 0) {
          hash = (37 * hash) + COLUMNVALUE_FIELD_NUMBER;
          hash = (53 * hash) + getColumnValueList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static protocolBuffer.TableProtos.Table.Row parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static protocolBuffer.TableProtos.Table.Row parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static protocolBuffer.TableProtos.Table.Row parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static protocolBuffer.TableProtos.Table.Row parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static protocolBuffer.TableProtos.Table.Row parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static protocolBuffer.TableProtos.Table.Row parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static protocolBuffer.TableProtos.Table.Row parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static protocolBuffer.TableProtos.Table.Row parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static protocolBuffer.TableProtos.Table.Row parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static protocolBuffer.TableProtos.Table.Row parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(protocolBuffer.TableProtos.Table.Row prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code protocolBuffer.Table.Row}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:protocolBuffer.Table.Row)
          protocolBuffer.TableProtos.Table.RowOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return protocolBuffer.TableProtos.internal_static_protocolBuffer_Table_Row_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return protocolBuffer.TableProtos.internal_static_protocolBuffer_Table_Row_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  protocolBuffer.TableProtos.Table.Row.class, protocolBuffer.TableProtos.Table.Row.Builder.class);
        }

        // Construct using protocolBuffer.TableProtos.Table.Row.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          columnValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return protocolBuffer.TableProtos.internal_static_protocolBuffer_Table_Row_descriptor;
        }

        public protocolBuffer.TableProtos.Table.Row getDefaultInstanceForType() {
          return protocolBuffer.TableProtos.Table.Row.getDefaultInstance();
        }

        public protocolBuffer.TableProtos.Table.Row build() {
          protocolBuffer.TableProtos.Table.Row result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public protocolBuffer.TableProtos.Table.Row buildPartial() {
          protocolBuffer.TableProtos.Table.Row result = new protocolBuffer.TableProtos.Table.Row(this);
          int from_bitField0_ = bitField0_;
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            columnValue_ = columnValue_.getUnmodifiableView();
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.columnValue_ = columnValue_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof protocolBuffer.TableProtos.Table.Row) {
            return mergeFrom((protocolBuffer.TableProtos.Table.Row)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(protocolBuffer.TableProtos.Table.Row other) {
          if (other == protocolBuffer.TableProtos.Table.Row.getDefaultInstance()) return this;
          if (!other.columnValue_.isEmpty()) {
            if (columnValue_.isEmpty()) {
              columnValue_ = other.columnValue_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureColumnValueIsMutable();
              columnValue_.addAll(other.columnValue_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          protocolBuffer.TableProtos.Table.Row parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (protocolBuffer.TableProtos.Table.Row) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private com.google.protobuf.LazyStringList columnValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureColumnValueIsMutable() {
          if (!((bitField0_ & 0x00000001) == 0x00000001)) {
            columnValue_ = new com.google.protobuf.LazyStringArrayList(columnValue_);
            bitField0_ |= 0x00000001;
           }
        }
        /**
         * <code>repeated string columnValue = 1;</code>
         */
        public com.google.protobuf.ProtocolStringList
            getColumnValueList() {
          return columnValue_.getUnmodifiableView();
        }
        /**
         * <code>repeated string columnValue = 1;</code>
         */
        public int getColumnValueCount() {
          return columnValue_.size();
        }
        /**
         * <code>repeated string columnValue = 1;</code>
         */
        public java.lang.String getColumnValue(int index) {
          return columnValue_.get(index);
        }
        /**
         * <code>repeated string columnValue = 1;</code>
         */
        public com.google.protobuf.ByteString
            getColumnValueBytes(int index) {
          return columnValue_.getByteString(index);
        }
        /**
         * <code>repeated string columnValue = 1;</code>
         */
        public Builder setColumnValue(
            int index, java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureColumnValueIsMutable();
          columnValue_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string columnValue = 1;</code>
         */
        public Builder addColumnValue(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureColumnValueIsMutable();
          columnValue_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string columnValue = 1;</code>
         */
        public Builder addAllColumnValue(
            java.lang.Iterable<java.lang.String> values) {
          ensureColumnValueIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, columnValue_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string columnValue = 1;</code>
         */
        public Builder clearColumnValue() {
          columnValue_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string columnValue = 1;</code>
         */
        public Builder addColumnValueBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureColumnValueIsMutable();
          columnValue_.add(value);
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:protocolBuffer.Table.Row)
      }

      // @@protoc_insertion_point(class_scope:protocolBuffer.Table.Row)
      private static final protocolBuffer.TableProtos.Table.Row DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new protocolBuffer.TableProtos.Table.Row();
      }

      public static protocolBuffer.TableProtos.Table.Row getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<Row>
          PARSER = new com.google.protobuf.AbstractParser<Row>() {
        public Row parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new Row(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Row> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Row> getParserForType() {
        return PARSER;
      }

      public protocolBuffer.TableProtos.Table.Row getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int TABLENAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object tableName_;
    /**
     * <code>required string tableName = 1;</code>
     */
    public boolean hasTableName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string tableName = 1;</code>
     */
    public java.lang.String getTableName() {
      java.lang.Object ref = tableName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tableName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string tableName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTableNameBytes() {
      java.lang.Object ref = tableName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tableName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COLUMNSNUMBER_FIELD_NUMBER = 2;
    private int columnsNumber_;
    /**
     * <code>required int32 columnsNumber = 2;</code>
     */
    public boolean hasColumnsNumber() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 columnsNumber = 2;</code>
     */
    public int getColumnsNumber() {
      return columnsNumber_;
    }

    public static final int ROWSNUMBER_FIELD_NUMBER = 3;
    private int rowsNumber_;
    /**
     * <code>required int32 rowsNumber = 3;</code>
     */
    public boolean hasRowsNumber() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 rowsNumber = 3;</code>
     */
    public int getRowsNumber() {
      return rowsNumber_;
    }

    public static final int COLUMNTYPES_FIELD_NUMBER = 4;
    private java.util.List<java.lang.Integer> columnTypes_;
    /**
     * <code>repeated int32 columnTypes = 4;</code>
     */
    public java.util.List<java.lang.Integer>
        getColumnTypesList() {
      return columnTypes_;
    }
    /**
     * <code>repeated int32 columnTypes = 4;</code>
     */
    public int getColumnTypesCount() {
      return columnTypes_.size();
    }
    /**
     * <code>repeated int32 columnTypes = 4;</code>
     */
    public int getColumnTypes(int index) {
      return columnTypes_.get(index);
    }

    public static final int COLUMNNAMES_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList columnNames_;
    /**
     * <code>repeated string columnNames = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getColumnNamesList() {
      return columnNames_;
    }
    /**
     * <code>repeated string columnNames = 5;</code>
     */
    public int getColumnNamesCount() {
      return columnNames_.size();
    }
    /**
     * <code>repeated string columnNames = 5;</code>
     */
    public java.lang.String getColumnNames(int index) {
      return columnNames_.get(index);
    }
    /**
     * <code>repeated string columnNames = 5;</code>
     */
    public com.google.protobuf.ByteString
        getColumnNamesBytes(int index) {
      return columnNames_.getByteString(index);
    }

    public static final int ROWS_FIELD_NUMBER = 6;
    private java.util.List<protocolBuffer.TableProtos.Table.Row> rows_;
    /**
     * <code>repeated .protocolBuffer.Table.Row rows = 6;</code>
     */
    public java.util.List<protocolBuffer.TableProtos.Table.Row> getRowsList() {
      return rows_;
    }
    /**
     * <code>repeated .protocolBuffer.Table.Row rows = 6;</code>
     */
    public java.util.List<? extends protocolBuffer.TableProtos.Table.RowOrBuilder> 
        getRowsOrBuilderList() {
      return rows_;
    }
    /**
     * <code>repeated .protocolBuffer.Table.Row rows = 6;</code>
     */
    public int getRowsCount() {
      return rows_.size();
    }
    /**
     * <code>repeated .protocolBuffer.Table.Row rows = 6;</code>
     */
    public protocolBuffer.TableProtos.Table.Row getRows(int index) {
      return rows_.get(index);
    }
    /**
     * <code>repeated .protocolBuffer.Table.Row rows = 6;</code>
     */
    public protocolBuffer.TableProtos.Table.RowOrBuilder getRowsOrBuilder(
        int index) {
      return rows_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTableName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasColumnsNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRowsNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tableName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, columnsNumber_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, rowsNumber_);
      }
      for (int i = 0; i < columnTypes_.size(); i++) {
        output.writeInt32(4, columnTypes_.get(i));
      }
      for (int i = 0; i < columnNames_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, columnNames_.getRaw(i));
      }
      for (int i = 0; i < rows_.size(); i++) {
        output.writeMessage(6, rows_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tableName_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, columnsNumber_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, rowsNumber_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < columnTypes_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(columnTypes_.get(i));
        }
        size += dataSize;
        size += 1 * getColumnTypesList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < columnNames_.size(); i++) {
          dataSize += computeStringSizeNoTag(columnNames_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getColumnNamesList().size();
      }
      for (int i = 0; i < rows_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, rows_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocolBuffer.TableProtos.Table)) {
        return super.equals(obj);
      }
      protocolBuffer.TableProtos.Table other = (protocolBuffer.TableProtos.Table) obj;

      boolean result = true;
      result = result && (hasTableName() == other.hasTableName());
      if (hasTableName()) {
        result = result && getTableName()
            .equals(other.getTableName());
      }
      result = result && (hasColumnsNumber() == other.hasColumnsNumber());
      if (hasColumnsNumber()) {
        result = result && (getColumnsNumber()
            == other.getColumnsNumber());
      }
      result = result && (hasRowsNumber() == other.hasRowsNumber());
      if (hasRowsNumber()) {
        result = result && (getRowsNumber()
            == other.getRowsNumber());
      }
      result = result && getColumnTypesList()
          .equals(other.getColumnTypesList());
      result = result && getColumnNamesList()
          .equals(other.getColumnNamesList());
      result = result && getRowsList()
          .equals(other.getRowsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasTableName()) {
        hash = (37 * hash) + TABLENAME_FIELD_NUMBER;
        hash = (53 * hash) + getTableName().hashCode();
      }
      if (hasColumnsNumber()) {
        hash = (37 * hash) + COLUMNSNUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getColumnsNumber();
      }
      if (hasRowsNumber()) {
        hash = (37 * hash) + ROWSNUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getRowsNumber();
      }
      if (getColumnTypesCount() > 0) {
        hash = (37 * hash) + COLUMNTYPES_FIELD_NUMBER;
        hash = (53 * hash) + getColumnTypesList().hashCode();
      }
      if (getColumnNamesCount() > 0) {
        hash = (37 * hash) + COLUMNNAMES_FIELD_NUMBER;
        hash = (53 * hash) + getColumnNamesList().hashCode();
      }
      if (getRowsCount() > 0) {
        hash = (37 * hash) + ROWS_FIELD_NUMBER;
        hash = (53 * hash) + getRowsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocolBuffer.TableProtos.Table parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocolBuffer.TableProtos.Table parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocolBuffer.TableProtos.Table parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocolBuffer.TableProtos.Table parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocolBuffer.TableProtos.Table parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocolBuffer.TableProtos.Table parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocolBuffer.TableProtos.Table parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocolBuffer.TableProtos.Table parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocolBuffer.TableProtos.Table parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocolBuffer.TableProtos.Table parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocolBuffer.TableProtos.Table prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocolBuffer.Table}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocolBuffer.Table)
        protocolBuffer.TableProtos.TableOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocolBuffer.TableProtos.internal_static_protocolBuffer_Table_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocolBuffer.TableProtos.internal_static_protocolBuffer_Table_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocolBuffer.TableProtos.Table.class, protocolBuffer.TableProtos.Table.Builder.class);
      }

      // Construct using protocolBuffer.TableProtos.Table.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRowsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        tableName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        columnsNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        rowsNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        columnTypes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        columnNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        if (rowsBuilder_ == null) {
          rows_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          rowsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocolBuffer.TableProtos.internal_static_protocolBuffer_Table_descriptor;
      }

      public protocolBuffer.TableProtos.Table getDefaultInstanceForType() {
        return protocolBuffer.TableProtos.Table.getDefaultInstance();
      }

      public protocolBuffer.TableProtos.Table build() {
        protocolBuffer.TableProtos.Table result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocolBuffer.TableProtos.Table buildPartial() {
        protocolBuffer.TableProtos.Table result = new protocolBuffer.TableProtos.Table(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.tableName_ = tableName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.columnsNumber_ = columnsNumber_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.rowsNumber_ = rowsNumber_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          columnTypes_ = java.util.Collections.unmodifiableList(columnTypes_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.columnTypes_ = columnTypes_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          columnNames_ = columnNames_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.columnNames_ = columnNames_;
        if (rowsBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            rows_ = java.util.Collections.unmodifiableList(rows_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.rows_ = rows_;
        } else {
          result.rows_ = rowsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocolBuffer.TableProtos.Table) {
          return mergeFrom((protocolBuffer.TableProtos.Table)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocolBuffer.TableProtos.Table other) {
        if (other == protocolBuffer.TableProtos.Table.getDefaultInstance()) return this;
        if (other.hasTableName()) {
          bitField0_ |= 0x00000001;
          tableName_ = other.tableName_;
          onChanged();
        }
        if (other.hasColumnsNumber()) {
          setColumnsNumber(other.getColumnsNumber());
        }
        if (other.hasRowsNumber()) {
          setRowsNumber(other.getRowsNumber());
        }
        if (!other.columnTypes_.isEmpty()) {
          if (columnTypes_.isEmpty()) {
            columnTypes_ = other.columnTypes_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureColumnTypesIsMutable();
            columnTypes_.addAll(other.columnTypes_);
          }
          onChanged();
        }
        if (!other.columnNames_.isEmpty()) {
          if (columnNames_.isEmpty()) {
            columnNames_ = other.columnNames_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureColumnNamesIsMutable();
            columnNames_.addAll(other.columnNames_);
          }
          onChanged();
        }
        if (rowsBuilder_ == null) {
          if (!other.rows_.isEmpty()) {
            if (rows_.isEmpty()) {
              rows_ = other.rows_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureRowsIsMutable();
              rows_.addAll(other.rows_);
            }
            onChanged();
          }
        } else {
          if (!other.rows_.isEmpty()) {
            if (rowsBuilder_.isEmpty()) {
              rowsBuilder_.dispose();
              rowsBuilder_ = null;
              rows_ = other.rows_;
              bitField0_ = (bitField0_ & ~0x00000020);
              rowsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRowsFieldBuilder() : null;
            } else {
              rowsBuilder_.addAllMessages(other.rows_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTableName()) {
          return false;
        }
        if (!hasColumnsNumber()) {
          return false;
        }
        if (!hasRowsNumber()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocolBuffer.TableProtos.Table parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocolBuffer.TableProtos.Table) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object tableName_ = "";
      /**
       * <code>required string tableName = 1;</code>
       */
      public boolean hasTableName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string tableName = 1;</code>
       */
      public java.lang.String getTableName() {
        java.lang.Object ref = tableName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            tableName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string tableName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTableNameBytes() {
        java.lang.Object ref = tableName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tableName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string tableName = 1;</code>
       */
      public Builder setTableName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        tableName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string tableName = 1;</code>
       */
      public Builder clearTableName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        tableName_ = getDefaultInstance().getTableName();
        onChanged();
        return this;
      }
      /**
       * <code>required string tableName = 1;</code>
       */
      public Builder setTableNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        tableName_ = value;
        onChanged();
        return this;
      }

      private int columnsNumber_ ;
      /**
       * <code>required int32 columnsNumber = 2;</code>
       */
      public boolean hasColumnsNumber() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 columnsNumber = 2;</code>
       */
      public int getColumnsNumber() {
        return columnsNumber_;
      }
      /**
       * <code>required int32 columnsNumber = 2;</code>
       */
      public Builder setColumnsNumber(int value) {
        bitField0_ |= 0x00000002;
        columnsNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 columnsNumber = 2;</code>
       */
      public Builder clearColumnsNumber() {
        bitField0_ = (bitField0_ & ~0x00000002);
        columnsNumber_ = 0;
        onChanged();
        return this;
      }

      private int rowsNumber_ ;
      /**
       * <code>required int32 rowsNumber = 3;</code>
       */
      public boolean hasRowsNumber() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 rowsNumber = 3;</code>
       */
      public int getRowsNumber() {
        return rowsNumber_;
      }
      /**
       * <code>required int32 rowsNumber = 3;</code>
       */
      public Builder setRowsNumber(int value) {
        bitField0_ |= 0x00000004;
        rowsNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 rowsNumber = 3;</code>
       */
      public Builder clearRowsNumber() {
        bitField0_ = (bitField0_ & ~0x00000004);
        rowsNumber_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> columnTypes_ = java.util.Collections.emptyList();
      private void ensureColumnTypesIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          columnTypes_ = new java.util.ArrayList<java.lang.Integer>(columnTypes_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated int32 columnTypes = 4;</code>
       */
      public java.util.List<java.lang.Integer>
          getColumnTypesList() {
        return java.util.Collections.unmodifiableList(columnTypes_);
      }
      /**
       * <code>repeated int32 columnTypes = 4;</code>
       */
      public int getColumnTypesCount() {
        return columnTypes_.size();
      }
      /**
       * <code>repeated int32 columnTypes = 4;</code>
       */
      public int getColumnTypes(int index) {
        return columnTypes_.get(index);
      }
      /**
       * <code>repeated int32 columnTypes = 4;</code>
       */
      public Builder setColumnTypes(
          int index, int value) {
        ensureColumnTypesIsMutable();
        columnTypes_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 columnTypes = 4;</code>
       */
      public Builder addColumnTypes(int value) {
        ensureColumnTypesIsMutable();
        columnTypes_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 columnTypes = 4;</code>
       */
      public Builder addAllColumnTypes(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureColumnTypesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, columnTypes_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 columnTypes = 4;</code>
       */
      public Builder clearColumnTypes() {
        columnTypes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList columnNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureColumnNamesIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          columnNames_ = new com.google.protobuf.LazyStringArrayList(columnNames_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string columnNames = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getColumnNamesList() {
        return columnNames_.getUnmodifiableView();
      }
      /**
       * <code>repeated string columnNames = 5;</code>
       */
      public int getColumnNamesCount() {
        return columnNames_.size();
      }
      /**
       * <code>repeated string columnNames = 5;</code>
       */
      public java.lang.String getColumnNames(int index) {
        return columnNames_.get(index);
      }
      /**
       * <code>repeated string columnNames = 5;</code>
       */
      public com.google.protobuf.ByteString
          getColumnNamesBytes(int index) {
        return columnNames_.getByteString(index);
      }
      /**
       * <code>repeated string columnNames = 5;</code>
       */
      public Builder setColumnNames(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureColumnNamesIsMutable();
        columnNames_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string columnNames = 5;</code>
       */
      public Builder addColumnNames(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureColumnNamesIsMutable();
        columnNames_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string columnNames = 5;</code>
       */
      public Builder addAllColumnNames(
          java.lang.Iterable<java.lang.String> values) {
        ensureColumnNamesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, columnNames_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string columnNames = 5;</code>
       */
      public Builder clearColumnNames() {
        columnNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string columnNames = 5;</code>
       */
      public Builder addColumnNamesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureColumnNamesIsMutable();
        columnNames_.add(value);
        onChanged();
        return this;
      }

      private java.util.List<protocolBuffer.TableProtos.Table.Row> rows_ =
        java.util.Collections.emptyList();
      private void ensureRowsIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          rows_ = new java.util.ArrayList<protocolBuffer.TableProtos.Table.Row>(rows_);
          bitField0_ |= 0x00000020;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          protocolBuffer.TableProtos.Table.Row, protocolBuffer.TableProtos.Table.Row.Builder, protocolBuffer.TableProtos.Table.RowOrBuilder> rowsBuilder_;

      /**
       * <code>repeated .protocolBuffer.Table.Row rows = 6;</code>
       */
      public java.util.List<protocolBuffer.TableProtos.Table.Row> getRowsList() {
        if (rowsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rows_);
        } else {
          return rowsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protocolBuffer.Table.Row rows = 6;</code>
       */
      public int getRowsCount() {
        if (rowsBuilder_ == null) {
          return rows_.size();
        } else {
          return rowsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protocolBuffer.Table.Row rows = 6;</code>
       */
      public protocolBuffer.TableProtos.Table.Row getRows(int index) {
        if (rowsBuilder_ == null) {
          return rows_.get(index);
        } else {
          return rowsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protocolBuffer.Table.Row rows = 6;</code>
       */
      public Builder setRows(
          int index, protocolBuffer.TableProtos.Table.Row value) {
        if (rowsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowsIsMutable();
          rows_.set(index, value);
          onChanged();
        } else {
          rowsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocolBuffer.Table.Row rows = 6;</code>
       */
      public Builder setRows(
          int index, protocolBuffer.TableProtos.Table.Row.Builder builderForValue) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.set(index, builderForValue.build());
          onChanged();
        } else {
          rowsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocolBuffer.Table.Row rows = 6;</code>
       */
      public Builder addRows(protocolBuffer.TableProtos.Table.Row value) {
        if (rowsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowsIsMutable();
          rows_.add(value);
          onChanged();
        } else {
          rowsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protocolBuffer.Table.Row rows = 6;</code>
       */
      public Builder addRows(
          int index, protocolBuffer.TableProtos.Table.Row value) {
        if (rowsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRowsIsMutable();
          rows_.add(index, value);
          onChanged();
        } else {
          rowsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protocolBuffer.Table.Row rows = 6;</code>
       */
      public Builder addRows(
          protocolBuffer.TableProtos.Table.Row.Builder builderForValue) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.add(builderForValue.build());
          onChanged();
        } else {
          rowsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocolBuffer.Table.Row rows = 6;</code>
       */
      public Builder addRows(
          int index, protocolBuffer.TableProtos.Table.Row.Builder builderForValue) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.add(index, builderForValue.build());
          onChanged();
        } else {
          rowsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protocolBuffer.Table.Row rows = 6;</code>
       */
      public Builder addAllRows(
          java.lang.Iterable<? extends protocolBuffer.TableProtos.Table.Row> values) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, rows_);
          onChanged();
        } else {
          rowsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protocolBuffer.Table.Row rows = 6;</code>
       */
      public Builder clearRows() {
        if (rowsBuilder_ == null) {
          rows_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          rowsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protocolBuffer.Table.Row rows = 6;</code>
       */
      public Builder removeRows(int index) {
        if (rowsBuilder_ == null) {
          ensureRowsIsMutable();
          rows_.remove(index);
          onChanged();
        } else {
          rowsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protocolBuffer.Table.Row rows = 6;</code>
       */
      public protocolBuffer.TableProtos.Table.Row.Builder getRowsBuilder(
          int index) {
        return getRowsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protocolBuffer.Table.Row rows = 6;</code>
       */
      public protocolBuffer.TableProtos.Table.RowOrBuilder getRowsOrBuilder(
          int index) {
        if (rowsBuilder_ == null) {
          return rows_.get(index);  } else {
          return rowsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protocolBuffer.Table.Row rows = 6;</code>
       */
      public java.util.List<? extends protocolBuffer.TableProtos.Table.RowOrBuilder> 
           getRowsOrBuilderList() {
        if (rowsBuilder_ != null) {
          return rowsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rows_);
        }
      }
      /**
       * <code>repeated .protocolBuffer.Table.Row rows = 6;</code>
       */
      public protocolBuffer.TableProtos.Table.Row.Builder addRowsBuilder() {
        return getRowsFieldBuilder().addBuilder(
            protocolBuffer.TableProtos.Table.Row.getDefaultInstance());
      }
      /**
       * <code>repeated .protocolBuffer.Table.Row rows = 6;</code>
       */
      public protocolBuffer.TableProtos.Table.Row.Builder addRowsBuilder(
          int index) {
        return getRowsFieldBuilder().addBuilder(
            index, protocolBuffer.TableProtos.Table.Row.getDefaultInstance());
      }
      /**
       * <code>repeated .protocolBuffer.Table.Row rows = 6;</code>
       */
      public java.util.List<protocolBuffer.TableProtos.Table.Row.Builder> 
           getRowsBuilderList() {
        return getRowsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          protocolBuffer.TableProtos.Table.Row, protocolBuffer.TableProtos.Table.Row.Builder, protocolBuffer.TableProtos.Table.RowOrBuilder> 
          getRowsFieldBuilder() {
        if (rowsBuilder_ == null) {
          rowsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              protocolBuffer.TableProtos.Table.Row, protocolBuffer.TableProtos.Table.Row.Builder, protocolBuffer.TableProtos.Table.RowOrBuilder>(
                  rows_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          rows_ = null;
        }
        return rowsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocolBuffer.Table)
    }

    // @@protoc_insertion_point(class_scope:protocolBuffer.Table)
    private static final protocolBuffer.TableProtos.Table DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocolBuffer.TableProtos.Table();
    }

    public static protocolBuffer.TableProtos.Table getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Table>
        PARSER = new com.google.protobuf.AbstractParser<Table>() {
      public Table parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Table(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Table> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Table> getParserForType() {
      return PARSER;
    }

    public protocolBuffer.TableProtos.Table getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocolBuffer_Table_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocolBuffer_Table_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocolBuffer_Table_Row_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocolBuffer_Table_Row_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036src/protocolBuffer/Table.proto\022\016protoc" +
      "olBuffer\"\264\001\n\005Table\022\021\n\ttableName\030\001 \002(\t\022\025\n" +
      "\rcolumnsNumber\030\002 \002(\005\022\022\n\nrowsNumber\030\003 \002(\005" +
      "\022\023\n\013columnTypes\030\004 \003(\005\022\023\n\013columnNames\030\005 \003" +
      "(\t\022\'\n\004rows\030\006 \003(\0132\031.protocolBuffer.Table." +
      "Row\032\032\n\003Row\022\023\n\013columnValue\030\001 \003(\tB\035\n\016proto" +
      "colBufferB\013TableProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protocolBuffer_Table_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocolBuffer_Table_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocolBuffer_Table_descriptor,
        new java.lang.String[] { "TableName", "ColumnsNumber", "RowsNumber", "ColumnTypes", "ColumnNames", "Rows", });
    internal_static_protocolBuffer_Table_Row_descriptor =
      internal_static_protocolBuffer_Table_descriptor.getNestedTypes().get(0);
    internal_static_protocolBuffer_Table_Row_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocolBuffer_Table_Row_descriptor,
        new java.lang.String[] { "ColumnValue", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
